apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-prod-config
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-demo-prod-deployment
  labels:
    source: demo
    app: spinnaker-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo
      app: spinnaker-prod
  template:
    metadata:
      labels:
        source: demo
        app: spinnaker-prod
    spec:
      containers:
      - name: primary
        image: index.docker.io/schaitanya/node-app
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo-prod
spec:
  selector:
    source: demo
    app: spinnaker-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
