apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: test-demo
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
  - port: 80
    targetPort: node-app-port
    name: http

